#!/bin/sh

XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null || true`"

for icon in `ls /opt/olive-editor/icons`;
do
	size="$(echo ${icon} | sed 's/[^0-9]//g')"
	"$XDG_ICON_RESOURCE" uninstall --size "${size}" "olive-editor"
done
